name: xops

networks:
  xops-net:
    external: true

services:
  deploy:
    build:
      context: ./deploy
      dockerfile: Dockerfile.deploy
    env_file:
      - ./deploy/.env.deploy
    volumes:
      - ./deploy:/app
    working_dir: /app
    ports:
      - "8007:8000"
    networks:
      - xops-net
    restart: unless-stopped


  train:
    build:
      context: ./train
      dockerfile: Dockerfile.train
    env_file:
      - ./train/.env.train
    volumes:
      - ./train:/app
    working_dir: /app
    ports:
      - "8888:8888"
    networks:
      - xops-net
    restart: unless-stopped